[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
    [headers.values]
      Content-Type = "text/html"

[[headers]]
  for = "/assets/*"
    [headers.values]
      Content-Type = "application/javascript"
